I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 220, in script
    call screen buttons2
  File "renpy/common/000statements.rpy", line 670, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
Exception: Screen buttons2 is not known.


-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 220, in script
    call screen buttons2
  File "/Users/vkumar/Downloads/renpy-8.1.3-sdk/renpy/ast.py", line 2259, in execute
    self.call("execute")
  File "/Users/vkumar/Downloads/renpy-8.1.3-sdk/renpy/ast.py", line 2241, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "/Users/vkumar/Downloads/renpy-8.1.3-sdk/renpy/statements.py", line 342, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 670, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "/Users/vkumar/Downloads/renpy-8.1.3-sdk/renpy/exports.py", line 3333, in call_screen
    show_screen(_screen_name, _transient=True, *args, **kwargs)
  File "/Users/vkumar/Downloads/renpy-8.1.3-sdk/renpy/display/screen.py", line 1220, in show_screen
    raise Exception("Screen %s is not known.\n" % (name[0],))
Exception: Screen buttons2 is not known.


macOS-13.1-arm64-arm-64bit arm64
Ren'Py 8.1.3.23091805
lovehurts 1.0
Thu Oct 12 03:31:41 2023
