I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 856, in script
    menu:
ScriptError: could not find label 'truebomb'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/vkumar/Downloads/renpy-8.1.1-sdk/renpy/bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "/Users/vkumar/Downloads/renpy-8.1.1-sdk/renpy/main.py", line 670, in main
    run(restart)
  File "/Users/vkumar/Downloads/renpy-8.1.1-sdk/renpy/main.py", line 144, in run
    renpy.execution.run_context(True)
  File "/Users/vkumar/Downloads/renpy-8.1.1-sdk/renpy/execution.py", line 953, in run_context
    context.run()
  File "game/script.rpy", line 856, in script
    menu:
  File "/Users/vkumar/Downloads/renpy-8.1.1-sdk/renpy/script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'truebomb'.

macOS-14.5-arm64-arm-64bit arm64
Ren'Py 8.1.1.23060707
lovehurts 1.0
Mon May 20 00:00:31 2024
