I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 97, in script
    call screen buttons
ScriptError: could not find label 's_label'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "/Users/vkumar/Downloads/renpy-8.1.3-sdk/renpy/bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "/Users/vkumar/Downloads/renpy-8.1.3-sdk/renpy/main.py", line 670, in main
    run(restart)
  File "/Users/vkumar/Downloads/renpy-8.1.3-sdk/renpy/main.py", line 144, in run
    renpy.execution.run_context(True)
  File "/Users/vkumar/Downloads/renpy-8.1.3-sdk/renpy/execution.py", line 955, in run_context
    context.run()
  File "game/script.rpy", line 97, in script
    call screen buttons
  File "/Users/vkumar/Downloads/renpy-8.1.3-sdk/renpy/script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 's_label'.

macOS-13.1-arm64-arm-64bit arm64
Ren'Py 8.1.3.23091805
lovehurts 1.0
Wed Sep 27 22:56:05 2023
